---
schema:
  - cc_number
  - cc_type
  - email
  - domain_name
  - ipv4
  - ipv6
  - password
  - jwt
  - phone_number
  - mac_address
  - url
  - username
  - toll_free_number
  - e_164_phone_number
  - title_male
  - title_female
  - first_name
  - first_name_male
  - first_name_female
  - last_name
  - name
  - gender
  - date
  - time
  - month_name
  - year
  - day_of_week
  - day_of_month
  - timestamp
  - century
  - timezone
  - time_period
  - word
  - sentence
  - paragraph
  - currency
  - amount_with_currency
  - uuid_digit
  - uuid_hyphenated
  - lat
  - long
  - unix_time
